WIP:Preventing special characters from being encoded in html
bullhorn/novo-elements pull request #1320
Opened 2022-06-13 20:03 UTC by antonyw89

## **Description**

INSERT A SMALL DESCRIPTION OF WHAT YOU CHANGED HERE

#### **Verify that...**

- [ ] Any related demos were added and `npm start` and `npm run build` still works
- [ ] New demos work in `Safari`, `Chrome` and `Firefox`
- [ ] `npm run lint` passes
- [ ] `npm test` passes and code coverage is increased
- [ ] `npm run build` still works

#### **Bullhorn Internal Developers**
- [ ] Run `Novo Automation`

##### **Screenshots**

2022-06-14 18:43 UTC, MichaelDill approved these changes

2022-06-14 18:53 UTC, ndickerson approved these changes

2022-06-17 13:59 UTC, bvkimball commented
Better description in PR please

2022-06-17 14:01 UTC, bvkimball requested changes
Better PR Description

2022-06-22 18:59 UTC, merged