Adding loading message to novo-loading component
bullhorn/novo-elements pull request #1332
Opened 2022-07-21 19:45 UTC by antonyw89

## **Description**

Adding a message and flag for the novo-loading component. This could be used to display a message while loading with the flag controlled at implementation. This can be used for a loading message displaying all the time for a loading screen, or having a timer flipping the flag to show a message during a long long loading screen. 

#### **Verify that...**

- [x] Any related demos were added and `npm start` and `npm run build` still works
- [x] New demos work in `Safari`, `Chrome` and `Firefox`
- [x] `npm run lint` passes
- [x] `npm test` passes and code coverage is increased
- [x] `npm run build` still works

#### **Bullhorn Internal Developers**
- [x] Run `Novo Automation`

##### **Screenshots**

![loadingMessage](https://user-images.githubusercontent.com/73492464/180301184-41be3115-2566-4ca8-ab80-3784667dc9fa.gif)

2022-07-22 15:52 UTC, ndickerson approved these changes

2022-07-23 23:56 UTC, bvkimball requested changes
I would rather transclude the text vs using a prop.
I also think we need to sync with UX on usage guidelines for this.

2022-07-26 17:44 UTC, antonyw89 commented
> I would rather transclude the text vs using a prop. I also think we need to sync with UX on usage guidelines for this.

Changed message to transcluded text. Also reached out to UX on the style and usage of the new features and received approval.

2022-07-26 18:10 UTC, bvkimball reviewed
I don't know if we should be using this or something else... would we need to add message to spinner too...

2022-07-26 18:10 UTC, bvkimball commented on projects/novo-elements/src/elements/loading/Loading.scss
> +    position: absolute;
when should the text wrap?

2022-07-26 20:42 UTC, closed without merging